USE [CultureGR]
GO

/****** Object:  Table [dbo].[CATEGORIESMUSEUMS]    Script Date: 18/1/2025 23:46:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORIESMUSEUMS](
	[cat_id] [int] NOT NULL,
	[cat_name] [nvarchar](50) NULL,
 CONSTRAINT [PK_CATEGORIESMUSEUMS] PRIMARY KEY CLUSTERED 
(
	[cat_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

select * from CATEGORIESMUSEUMS 
order by cat_id asc

delete from CATEGORIESMUSEUMS;
