USE [CultureGR]
GO

/****** Object:  Table [dbo].[ARCHAEOLOGICAL_POINTS]    Script Date: 18/1/2025 10:31:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ARCHAEOLOGICAL_POINTS](
	[arc_id] [int] IDENTITY(1,1) NOT NULL,
	[arc_name] [nvarchar](50) NULL,
	[arc_location] [nvarchar](50) NULL,
	[archaeological_exh_id] [int] NOT NULL,
	[archaeological_per_id] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ARCHAEOLOGICAL_POINTS]  WITH CHECK ADD  CONSTRAINT [FK_ARCHAEOLOGICAL_POINTS_EXHIBITS] FOREIGN KEY([archaeological_exh_id])
REFERENCES [dbo].[EXHIBITS] ([exh_id])
GO

ALTER TABLE [dbo].[ARCHAEOLOGICAL_POINTS] CHECK CONSTRAINT [FK_ARCHAEOLOGICAL_POINTS_EXHIBITS]
GO

ALTER TABLE [dbo].[ARCHAEOLOGICAL_POINTS]  WITH CHECK ADD  CONSTRAINT [FK_ARCHAEOLOGICAL_POINTS_TIME_PERIODS] FOREIGN KEY([archaeological_per_id])
REFERENCES [dbo].[TIME_PERIODS] ([p_id])
GO

ALTER TABLE [dbo].[ARCHAEOLOGICAL_POINTS] CHECK CONSTRAINT [FK_ARCHAEOLOGICAL_POINTS_TIME_PERIODS]
GO


drop table ARCHAEOLOGICAL_POINTS
go